"1. hello world"
"2. https://www.hackerrank.com/challenges/py-if-else/problem?isFullScreen=true"
"3. https://www.hackerrank.com/challenges/python-arithmetic-operators/problem?isFullScreen=true"
"4. https://www.hackerrank.com/challenges/python-division/problem?isFullScreen=true"
"5. https://www.hackerrank.com/challenges/python-loops/problem?isFullScreen=true"
"6. https://www.hackerrank.com/challenges/write-a-function/problem?isFullScreen=true"
"7. https://www.hackerrank.com/challenges/python-print/problem?isFullScreen=true"